version: "3"
services:
  ossrf-dev:
    build:
      dockerfile: ./dev/Dockerfile
    image: ossrf-dev
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - ../volumes/home:/home/nmos/
    network_mode: host

  nmos-registry:
    image: docker.io/rhastie/nmos-cpp:latest
    network_mode: host
