version: "3"
services:
  ossrf-dev:
    build:
      dockerfile: ./dev/Dockerfile
    image: ossrf-dev
    environment:
      - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
      - DISPLAY:$DISPLAY
      - TZ=Europe/Lisbon
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../volumes/home:/home/nmos/
      - /.conan2:/home/nmos/.conan2:rw
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    network_mode: host
    privileged: true

  nmos-registry:
    image: docker.io/rhastie/nmos-cpp:latest
    network_mode: host
